### ISSUE TITLE
Update to KeyBox 2.85.03

### ISSUE THREAD

**Issue by anthony-o** [aditosoftware/docker-keybox#2]
Since the version you build from (2.85.01), 2 new [releases](https://github.com/skavanagh/KeyBox/releases) have been created.
Could you update to the last one?

**Comment by anthony-o** [comment]
This could not be as tricky as it seems as there are [5 new properties parameters](https://github.com/skavanagh/KeyBox/commit/7357b5a85e5e29b0b3fc73fbc9cda5978961376d#diff-492f27a5044cce8470c2303ab98a06f5R43):
- `dbPath`
- `maxActive`
- `testOnBorrow`
- `minIdle`
- `maxWait`

**Comment by bdito** [comment]
Yeah, its a bit tricky to add these variables. But I have done that, the new docker-image is now available.
