### ISSUE TITLE
Mount jaas.conf file

### ISSUE THREAD

**Issue by Laayem** [aditosoftware/docker-keybox#6]
Hi, 

I've got some troubles to enable ldap-ad authentication on your image.
I don't know where to mount the jaas.conf, I've tried /a/jaas.conf but it didn't seem to work.

This is the command : 
```
docker run -v /opt/docker/aditokeybox:/a/keydb -v /opt/docker/aditokeybox/jaas.conf:/a/jaas.conf -p 8443:8443 -e jaasModule=ldap-ad adito/keybox
```
Is there anything wrong? 

Thank you

**Comment by bdito** [comment]
Try this:
`docker run -v /opt/docker/aditokeybox:/a/keydb -v /opt/docker/aditokeybox/jaas.conf:/opt/KeyBox-jetty/jetty/keybox/WEB-INF/classes/jaas.conf -p 8443:8443 -e jaasModule=ldap-ad adito/keybox`

**Comment by Laayem** [comment]
Thank you for your quick reply. It work like a charm!
