### ISSUE TITLE
Tag suggestion for Docker Hub project

### ISSUE THREAD

**Issue by herokang** [aditosoftware/docker-keybox#9]
Hi, 
I am Kang Yin, a graduate student of Institute of Software, Chinese Academy of Sciences. Now we are doing a research on how to recommend tags for Docker Hub’s projects. We applied text mining and natural language processing to build a tag recommendation system for Docker projects.
We notice that you have created a repository on Docker Hub, which is named _adito/keybox_ and the project address is [https://hub.docker.com/r/adito/keybox/](https://hub.docker.com/r/adito/keybox/) 
Since the developers knows their projects better, we want to evaluate our recommendation results with your help as the project developer. We want to know if the recommended tags are reasonable for your projects. 
The following tags (ranked by order) are generated from our model automatically. Would you like to do me a favor and reply with what tags are reasonable (Good) and what are not (Bad), in form of, “Good tags: ***, ***; Bad tags: ***, ***”.

The recommend tags for your project are listed as follows:

> `keybox, key, ssh, public ssh key, connection, key-management, connection-pool, public-key, ssh-keys, key-pair`

It will be a great help if you can give us a feedback. 
Thank you so much for your precious time.

**Comment by bdito** [comment]
Good tags: keybox, key-management, public-key, ssh-keys, key-pair, ssh, public ssh key, key
Bad tags: connection, connection-pool,
